### ISSUE TITLE
Respect prettier format

### ISSUE THREAD

**Issue by rwu823** [rikukissa/typehole#16]
Could it detect if there is a prettier in the project then use the prettier format in the automatically generated type

**Comment by rikukissa** [comment]
Totally could, and I was actually just now looking at why that feature doesn't work currently in the extension (it should). Apparently, I've at least made a mistake there that leads the formatting to only apply for the file currently open and not the one where the type appeared. It will be fixed in the next release

**Comment by rikukissa** [comment]
Should be fixed and respect the selected formatter in [1.6.1](https://github.com/rikukissa/typehole/releases/tag/1.6.1)
